config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/upsc_ai_mobile", to: "graphql#execute"
  post '/login_upsc_ai_mobile', to: 'graph_ql_sessions#create' # Login endpoint
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  authenticate :admin_user, lambda { |u| u } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :internal_api do
    resources :create_order, only: [:create]
    resources :update_payment, only: [:create]
    resources :refresh_status, only: [:index]
  end

  namespace :mobile_app_api do
    resources :login, only: [:create]
    resources :validate_auth_token, only: [:index]
    resources :user_profile_data, only: [:index]
    resources :get_questions, only: [:index]
    resources :create_question, only: [:create]
  end

  resources :fetch_data, only: [:index]

  root to: "admin/dashboard#index"

end

app/models/question.rb
class Question < ApplicationRecord
   belongs_to :admin_user
   belongs_to :paper
   has_many :keyword, dependent: :destroy
   has_many :answer, dependent: :destroy
   has_many :answer_error, dependent: :destroy

   enum answer_generation_status: ["Generated", "Your Answer Generation Is In Progress", "Error"]

   after_create :generate_the_answer
   validate :check_token_balance, on: :create

   def check_token_balance
      if self.admin_user.user_plan.balanced_token <= 0
        errors.add(:base, "Not enough tokens to generate the answer")
      end
   end

   def generate_the_answer
      self.update({answer_generation_status: 1})
      create_keywords
      if self.admin_user.user_plan.balanced_token > 0
         GetAnswerJob.perform_async(self.id)
      end
   end

   def create_keywords
      self.comma_separated_keywords.split(",").each do |key|
        Keyword.create(keyword: key, admin_user: self.admin_user, question: self, paper: self.paper)
      end
   end

   def only_generate_the_answer
      if self.admin_user.user_plan.balanced_token > 0
         GetAnswerJob.perform_async(self.id)
      end
   end


   def answer_status_html
      answer_html = <<-HTML
                       HTML
      @answer_error = answer_error.where.not(status: "Solved").order(:error_date_time).last

      if !@answer_error.nil? && answer_generation_status == "Error"

        admin_message = <<-HTML
                        <div id='admin_message'>
                        <br/><strong>Message for Admin:</strong>
                        <p>#{@answer_error.message}</p>
                        </div>
                        HTML
        answer_html = <<-HTML
                        <div class="col-md-12 alert alert-danger refresh_status" role="alert" id=#{id}>
                           Opps Something went wrong! #{@answer_error.status.humanize}
                           #{admin_message}
                        </div>
                        HTML
      elsif answer_generation_status == "Your Answer Generation Is In Progress"
         answer_html = <<-HTML
                        <div class="col-md-12 alert alert-warning refresh_status" role="alert" id=#{id}>
                           #{answer_generation_status}
                        </div>
                     HTML
      elsif answer_generation_status == "Generated"
         ans_str = ""
         answer.each do |ans|

            ans_str +=  "<div class='card mb-3 bgimg no_more_refresh'>
                              <div class='card-body'>
                                 <div class='row d-flex justify-content-center pt-4' >
                                       <div class='col-md-8 mt-5'>
                                          <p class='text-justify text-dark' style='font-size: 135%;'>#{ans.get_formated_answer}</p>
                                       </div>
                                 </div>
                              </div>
                              <div class='col-md-12'>
                                 <span class='badge rounded-pill bg-secondary'>Charged Token: #{ans.charged_token}</span>
                              </div>
                           </div>"
         end
         answer_html = <<-HTML
                       #{ans_str}
                       HTML
      end
    end


end

app/views/admin/questions/_show.html.erb
<div class="isolated_bs">
    <style type="text/css">
        <% if current_admin_user.role != 'admin' %>
             #admin_message {
                display: none
             }
        <% end %>
        @media only screen and (min-width: 1200px) and (max-width: 1400px) {
            .bgimg {
                background-image: url('/upscsheetmain.png');
                background-repeat: no-repeat;
                background-position: center; 
                height: 1200px;
            }
        }
    </style>
    <div class="card mb-3">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <strong style="font-size: 18px;">Q: <%= @question.question %></strong>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 text-center">
                    <span class="badge rounded-pill bg-primary"><%= @question.paper.name %></span>
                </div>
                <div class="col-md-8 text-right">
                    <% @question.keyword.each do |key| %>
                      <span class="badge rounded-pill bg-secondary"><%= key.keyword %></span>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <div id='answer_div'>
     <%= @question.answer_status_html.html_safe %>
    </div>
</div>